fields:
  - name: id
    type: integer
  - name: code
    type: integer
    constraints:
      required: true
  - name: seq
    type: integer
    constraints:
      required: true
  - name: name
    type: string
  - name: title
    type: string
  - name: description
    type: string
  - name: valid_from
    type: string
    contraints:
      required: true
      pattern: '\d{4}-\d{2}'
  - name: valid_to
    type: string
    contraints:
      required: true
      pattern: '\d{4}-\d{2}'
  - name: created_at
    type: datetime
    constraints:
      required: true
  - name: updated_at
    type: datetime
    constraints:
      required: true
primaryKey:
  - id
